<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/NumPy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#NumPy Array Shape
#shape: NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.
#Integers at every index tells about the number of elements the corresponding dimension has.

import numpy as np

arr = np.array([[1,2,3,4], [2,5,7,9]])
print(arr)
print('\n')
print(arr.shape)

#Output: (2,4) meaning: 2 dimensions, and each dimension has 4 elements.
#The shape of an array is the number of elements in each dimension.

[[1 2 3 4]
 [2 5 7 9]]


(2, 4)


In [6]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('\n')
print(arr.shape)

[[[[[1 2 3 4]]]]]


(1, 1, 1, 1, 4)


In [9]:
#NumPy Array Reshaping

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1-D array with 12 elements into a 2-D array
print(arr)
print('\n')

new_arr = arr.reshape(4,3)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1-D array with 12 elements into a 3-D array
print(arr)
print('\n')

new_arr = arr.reshape(2,3,2)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
#Check if the returned array is a copy or a view.
print(arr.reshape(4,3).base)

#It is view because return original array.

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
#Unknown dimmension
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

#We do not have to specify an exact number for one of the dimensions in the reshape method.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
#Flattening the arrays
#Flattening array means converting a multidimensional array into a 1D array.
#We can use reshape(-1) to do this.

arr = np.array([[1,2,3,4],[2,4,6,8]])
print(arr, '\n')

new_arr = arr.reshape(-1)
print(new_arr)

[[1 2 3 4]
 [2 4 6 8]] 

[1 2 3 4 2 4 6 8]


In [16]:
#Array Iterating

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for x in arr:
  print(x)

1
2
3
4
5
6
7
8


In [18]:
arr = np.array([[1,2,3,4],[2,4,6,8]])

#It'll Iterate on the elements of the following 2-D array.
for x in arr:
  print(x)

[1 2 3 4]
[2 4 6 8]


In [19]:
#To return the actual values, the scalars, we have to iterate the arrays in each dimension.

for x in arr:
  for y in x:
    print(y)

1
2
3
4
2
4
6
8


In [25]:
#Iterating 3D arrays.
arr = np.array([[[1,2,3],[2,3,5]], [[2,7,9], [9, 0, 7]]])
print(arr, '\n')

for x in arr:
  print(x)

print('\n')

for x in arr:
  for y in x:
    print(y)

print('\n')

for x in arr:
  for y in x:
    for z in y:
      print(z)

[[[1 2 3]
  [2 3 5]]

 [[2 7 9]
  [9 0 7]]] 

[[1 2 3]
 [2 3 5]]
[[2 7 9]
 [9 0 7]]


[1 2 3]
[2 3 5]
[2 7 9]
[9 0 7]


1
2
3
2
3
5
2
7
9
9
0
7


In [27]:
#Iterating Arrays Using nditer()
#In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to 
#write for arrays with very high dimensionality.

arr = np.array([[[1,2,3],[2,3,5]], [[2,7,9], [9, 0, 7]]])
print(arr, '\n')

for x in np.nditer(arr):
  print(x)

[[[1 2 3]
  [2 3 5]]

 [[2 7 9]
  [9 0 7]]] 

1
2
3
2
3
5
2
7
9
9
0
7


In [29]:
#Iterating Array With Different Data Types.

'''
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, 
that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [32]:
#Iterating through every scalar element of the 2D array skipping 1 element.
arr = np.array([[1,2,3,4],[2,4,6,8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
2
6


In [33]:
#Enumerated Iteration Using ndenumerate()
#Enumeration means mentioning sequence number of somethings one by one.

#Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for indx, x in np.ndenumerate(arr):
  print(indx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8


In [34]:
arr = np.array([[1,2,3,4],[2,4,6,8]])
for indx, x in np.ndenumerate(arr):
  print(indx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 2
(1, 1) 4
(1, 2) 6
(1, 3) 8


In [35]:
#NumPy Joining array.
#Joining means putting contents of two or more arrays in a single array.
#in NumPy we join arrays by axes.
#We pass a sequence of arrays that we want to join to the concatenate() function, 
#along with the axis. If axis is not explicitly passed, it is taken as 0.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [38]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [41]:
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
#We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2)) #hstack() to stack along rows.

print(arr)

[1 2 3 4 5 6]


In [43]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2)) #vstack()  to stack along columns.

print(arr)

[[1 2 3]
 [4 5 6]]


In [44]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2)) #dstack() to stack along height, which is the same as depth.

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
