<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#NumPy: Numerical Python
#NumPy is used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices.

#NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

#NumPy is 50 times faster than traditional Python List.
#NumPy arrays follows locality of reference.
#NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
#It is optimized to work with latest CPU architectures.

#NumPy written in python,C and C++.

In [32]:
import numpy as np

In [33]:
#NumPy version

print(np.__version__)

1.19.5


In [34]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

#NumPy is used to work with arrays. The array object in NumPy is called ndarray.

#We can create a NumPy ndarray object by using the array() function.

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [35]:
#0-D arrays/scalar with one value.
a = np.array(34)
print(a)
print(type(a))

34
<class 'numpy.ndarray'>


In [36]:
#1-D array: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
b = np.array([1,2,3,4,5])
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [37]:
#2-D Arrays: An array that has 1-D arrays as its elements is called a 2-D array.
c = np.array([[1,2,3,4,5], [2,3,4,5,6],[9,8,7,6,5]])
print(c)
print(type(c))

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 6 5]]
<class 'numpy.ndarray'>


In [38]:
#3-D arrays: An array that has 2-D arrays (matrices) as its elements is called 3-D array.
d = np.array([[[1,2,3], [2,3,4]], [[9,8,7], [1,2,3]]])
print(d)
print(type(d))

[[[1 2 3]
  [2 3 4]]

 [[9 8 7]
  [1 2 3]]]
<class 'numpy.ndarray'>


In [39]:
#ndim: returns an integer that tells us how many dimensions the array have.

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [40]:
#An array can have any number of dimensions.

arr = np.array([1,2,3,4], ndmin=4)
print(arr)
print(arr.ndim)

[[[[1 2 3 4]]]]
4


In [41]:
#Array indexing
arr = np.array([1,2,3,4,5])
print(arr[0]) 
print(arr[1])
print(arr[0] + arr[1])

1
2
3


In [42]:
#accessing 2D array: To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
c = np.array([[1,2,3,4,5], [2,3,4,5,6],[9,8,7,6,5]])
print(c[0,1])

2


In [43]:
#3D:
d = np.array([[[1,2,3], [2,3,4]], [[9,8,7], [1,2,3]]])
print(d[0,1,0])

2


In [44]:
#Print the last element from the 2nd dim.

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
