<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Array Slicing: taking elements from one given index to another given index.
# [start:end]
# [start:end:step]

'''
If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

'''

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:5]) #End position excluded and start position is included.

[2 3 4 5]


In [4]:
print(arr[1:])

[2 3 4 5 6 7 8 9]


In [5]:
print(arr[:5])

[1 2 3 4 5]


In [9]:
#Negative slicing.
print(arr[-4:-1]) #-1 postion is excluded.

[6 7 8]


In [12]:
#step size.
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:5:2])

[2 4]


In [13]:
print(arr[::2])

[1 3 5 7 9]


In [14]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [16]:
#From both elements, return index 2.
print(arr[0:2, 2]) #0:2 specify elements in 2D array which is 1D array elements.

[3 8]


In [18]:
#From both elements, slice index 1 to index 4 (not included).
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
#Data Types in NumPy.
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

'''

#dtype: returns the data type of the array.

In [19]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [20]:
arr = np.array(['saurav', 'IITI', 'MS-CSE'])
print(arr.dtype)

<U6


In [22]:
#array() function to create arrays, this function can take an optional argument: dtype

arr = np.array([1,2,3,4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [23]:
#data type 4 bytes integer.
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [24]:
#The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [25]:
#Changing data type from integer to boolean
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [26]:
#NumPy copy and View
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

'''
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
'''

[42  2  3  4  5]
[42  2  3  4  5]


In [29]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

#The copy returns None.
#The view returns the original array.

None
[1 2 3 4 5]
