<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/NumPy_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##____NumPy ufunc____##

#NumPy Summations
#Addition is done between two arguments whereas summation happens over n elements.

In [1]:
import numpy as np

In [2]:
#Adding the values in arr1 to the values in arr2.

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [4]:
#Sum the values in arr1 and the values in arr2.

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [5]:
#Perform summation.

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1) #axis=1, NumPy will sum the numbers in each array.

print(newarr)

[6 6]


In [6]:
#Cummulative Sum
#Cummulative sum means partially adding the elements in array.

#The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
#cumsum() function: performs the cummulative sum.

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [8]:
#NumPy Products
#prod() function:product of the elements in an array.
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x) # 1*2*3*4

24


In [9]:
#Finding the product of the elements of two arrays.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])  #1*2*3*4*5*6*7*8 

print(x)  

40320


In [10]:
#axis=1, NumPy will return the product of each array.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [11]:
#cumprod() function:The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [ ]:
#NumPy Differences.
#A discrete difference means subtracting two successive elements.

#for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]  :diff() function

In [13]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)  #15-10=5, 25-15=10, and 5-25=-20

print(newarr)

#We can perform this operation repeatedly by giving parameter n.

[  5  10 -20]


In [14]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2) #15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30

print(newarr)

[  5 -30]


In [15]:
#NumPy LCM Lowest Common Multiple.
#least number that is common multiple of both of the numbers.

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [16]:
#The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [18]:
arr = np.arange(1, 11)
print(arr)
x = np.lcm.reduce(arr)

print(x)

[ 1  2  3  4  5  6  7  8  9 10]
2520


In [19]:
#NumPy GCD Greatest Common Denominator.
#The biggest number that is a common factor of both of the numbers.
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [20]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [21]:
#NumPy Set Operations.

# unique() method to find unique elements from any array.

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [22]:
#union1d() method: To find the unique values of two arrays.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [28]:
#Finding Intersection

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

'''
the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
It should always be set to True when dealing with sets.

'''

[3 4]


'\nthe intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. \nIt should always be set to True when dealing with sets.\n\n'

In [29]:
#Finding Difference.

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)


[1 2]


In [31]:
#Finding Symmetric Difference.
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)
#To find only the values that are NOT present in BOTH sets.

[1 2 5 6]
