<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/NumPy_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#_____NumPy ufunc_____#

#ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.
#ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

'''
ufunc also take additional arguments:

where: boolean array or condition defining where the operations should take place.

dtype: defining the return type of elements.

out: output array where the return value should be copied.

'''
#What is Vectorization?
#Converting iterative statements into a vector based operation is called vectorization.

#It is faster as modern CPUs are optimized for such operations.

'\nufunc also take additional arguments:\n\nwhere: boolean array or condition defining where the operations should take place.\n\ndtype: defining the return type of elements.\n\nout: output array where the return value should be copied.\n\n'

In [4]:
#Adding the Elements of Two Lists.
#without ufunc.

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [5]:
#NumPy has a ufunc for this, called add(x, y) that will produce the same result.

#With ufunc.

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [ ]:
#Create Your Own ufunc
'''
To create you own ufunc, you have to define a function, like you do with normal functions in Python, 
then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.
'''

In [15]:
#Creating your own ufunc for addition.

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))
print(type(np.add))   #Checking the type of a function to check if it is a ufunc or not.
print(type(myadd))

[6 8 10 12]
<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


In [13]:
#another wat to check the type.
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [16]:
#Simple Arithmetic
#The add() function sums the content of two arrays, and return the results in a new array.

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [17]:
#The subtract() function subtracts the values from one array with the values from another array, 
#and return the results in a new array.
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [18]:
#The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [19]:
#The divide() function divides the values from one array with the values from another array, and return the results in a new array.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [20]:
#The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [22]:
#Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, 
#and return the results in a new array.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
newaar = np.remainder(arr1, arr2)

print(newarr)
print(newaar)

[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


In [23]:
#The divmod() function return both the quotient and the the mod. The return value is two arrays, 
#the first array contains the quotient and second array contains the mod.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [25]:
#Both the absolute() and the abs() functions functions do the same absolute operation element-wise but we should use absolute() 
#to avoid confusion with python's inbuilt math.abs()

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)
newaar = np.abs(arr)

print(newarr)
print(newaar)

[1 2 1 2 3 4]
[1 2 1 2 3 4]


#Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

*  truncation
*  fix
*  rounding
*  floor
*  ceil

In [27]:
#Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

arr = np.trunc([-3.1666, 3.6667])
aar = np.fix([-3.1666, 3.6667])

print(arr)
print(aar)

[-3.  3.]
[-3.  3.]


In [28]:
#Rounding
#The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

arr = np.around(3.1666, 2)

print(arr)

3.17


In [30]:
#Floor
#The floor() function rounds off decimal to nearest lower integer.

arr = np.floor([-3.1666, 3.6667])

print(arr)

#Note: The floor() function returns floats, unlike the trunc() function who returns integers.

[-4.  3.]


In [31]:
#Ceil
#The ceil() function rounds off decimal to nearest upper integer.

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [32]:
#NumPy Logs
#NumPy provides functions to perform log at the base 2, e and 10.

#Log at Base 2
#Use the log2() function to perform log at the base 2.

arr = np.arange(1, 10)

print(arr)
print(np.log2(arr))

#Note: The arange(1, 10) function returns an array with integers starting from 1 (included) to 10 (not included).

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [34]:
#Log at Base 10
#Use the log10() function to perform log at the base 10.

arr = np.arange(1, 10)

print(arr)
print(np.log10(arr))

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [36]:
#Natural Log, or Log at Base e
#Use the log() function to perform log at the base e.

arr = np.arange(1, 10)

print(arr)
print(np.log(arr))

[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
