<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/PyTorch_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
############################________Linear Regression With PyTorch FrameWork With Built-in function__________###############################

In [5]:
#PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.
import torch
import torch.nn as nn
import numpy as np

#torch.nn package contains utility classes for building neural networks.

In [7]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

input = torch.from_numpy(inputs)
target = torch.from_numpy(targets)

#TensorDataset and DataLoader



*   TensorDataset, which allows access to rows from inputs and targets as tuples.
*   The TensorDataset allows us to access a small section of the training data using the array indexing notation.
*   It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.
*   DataLoader can split the data into batches of a predefined size while training. 
*   It also provides other utilities like shuffling and random sampling of the data.



In [13]:
from torch.utils.data import TensorDataset

# Defining the dataset
train_ds = TensorDataset(input, target)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [19]:
from torch.utils.data import DataLoader

# Defining data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [21]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

#In each iteration, the data loader returns one batch of data with the given batch size. 
#If shuffle is set to True, it shuffles the training data before creating batches. 
#Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

tensor([[ 87., 134.,  58.],
        [ 87., 135.,  57.],
        [ 91.,  87.,  65.],
        [ 91.,  88.,  64.],
        [ 92.,  87.,  64.]])
tensor([[119., 133.],
        [118., 134.],
        [ 80., 102.],
        [ 81., 101.],
        [ 82., 100.]])


In [22]:
#For Help we can type like.

#  ?DataLoader

In [28]:
#    nn.Linear

#Instead of initializing the weights & biases manually, we can define the model using the nn.Linear class from PyTorch, which does it automatically.
# Defining model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2276,  0.2758, -0.0487],
        [ 0.3411, -0.5269,  0.2057]], requires_grad=True)
Parameter containing:
tensor([0.5319, 0.5621], requires_grad=True)


In [31]:
# .parameters 

#PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model. 
#For our linear regression model, we have one weight matrix and one bias matrix.
# Parameters

list(model.parameters())

[Parameter containing:
 tensor([[-0.2276,  0.2758, -0.0487],
         [ 0.3411, -0.5269,  0.2057]], requires_grad=True),
 Parameter containing:
 tensor([0.5319, 0.5621], requires_grad=True)]

In [32]:
# Generating the predictions.
prediction_ = model(input)
prediction_

tensor([[ 2.9538e-01, -9.9384e-01],
        [ 9.6581e-01, -1.5984e+00],
        [ 1.4854e+01, -2.8434e+01],
        [-1.2633e+01,  2.0308e+01],
        [ 7.8879e+00, -1.2082e+01],
        [-2.0805e-01, -1.2589e-01],
        [ 6.4131e-01, -8.6582e-01],
        [ 1.4578e+01, -2.7887e+01],
        [-1.2129e+01,  1.9440e+01],
        [ 8.0669e+00, -1.2218e+01],
        [-2.9118e-02, -2.6121e-01],
        [ 4.6238e-01, -7.3050e-01],
        [ 1.5179e+01, -2.9166e+01],
        [-1.2812e+01,  2.0443e+01],
        [ 8.3914e+00, -1.2950e+01]], grad_fn=<AddmmBackward>)

In [35]:
#Loss Function

#Instead of defining a loss function manually, we can use the built-in loss function mse_loss.
#The nn.functional package contains many useful loss functions and several other utilities.

# Importing nn.functional
import torch.nn.functional as F

# Defining the loss function
loss_fn = F.mse_loss

In [36]:
#Computing the loss for the current predictions of our model.

loss = loss_fn(prediction_, target)
print(loss)

tensor(8944.8076, grad_fn=<MseLossBackward>)


In [37]:
#Optimizer

#Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer optim.SGD. 
#SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.

# Defining optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

#Note that model.parameters() is passed as an argument to optim.SGD so that the optimizer knows which matrices should be modified during the update step. 
#Also, we can specify a learning rate that controls the amount by which the parameters are modified.

#Training the model.

*  Generate predictions

*  Calculate the loss

*  Compute gradients w.r.t the weights and biases

*  Adjust the weights by subtracting a small quantity proportional to the gradient

*  Reset the gradients to zero

We'll work batches of data instead of processing the entire training data in every iteration. We defined a utility function fit that trains the model for a given number of epochs.

In [39]:
# Utility function to training the model

def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generating predictions
            pred = model(xb)
            
            # 2. Calculating loss
            loss = loss_fn(pred, yb)
            
            # 3. Computing gradients 
            loss.backward()
            
            # 4. Update parameters using gradients--Instead of updating parameters (weights and biases) manually, we use opt.step to perform the update.
            opt.step()
            
            # 5. Reset the gradients to zero--opt.zero_grad to reset the gradients to zero.
            opt.zero_grad()
        
        # Print the progress --prints the loss from the last batch of data for every 10th epoch to track training progress. 
        #loss.item returns the actual value stored in the loss tensor.
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))  

In [41]:
fit(200, model, loss_fn, opt, train_dl)

Epoch [10/200], Loss: 19.8506
Epoch [20/200], Loss: 22.5004
Epoch [30/200], Loss: 13.8141
Epoch [40/200], Loss: 12.1865
Epoch [50/200], Loss: 12.5050
Epoch [60/200], Loss: 4.2958
Epoch [70/200], Loss: 5.6107
Epoch [80/200], Loss: 3.9160
Epoch [90/200], Loss: 6.8802
Epoch [100/200], Loss: 9.1331
Epoch [110/200], Loss: 7.3606
Epoch [120/200], Loss: 4.2813
Epoch [130/200], Loss: 5.2800
Epoch [140/200], Loss: 4.3814
Epoch [150/200], Loss: 5.6619
Epoch [160/200], Loss: 7.2535
Epoch [170/200], Loss: 4.3161
Epoch [180/200], Loss: 4.4131
Epoch [190/200], Loss: 2.6443
Epoch [200/200], Loss: 3.5485


In [44]:
#Comaparing with actual target.
# Generating predictions

prediction_ = model(input)
print(prediction_)
print(target)

tensor([[ 57.2305,  70.6597],
        [ 80.6012,  99.8181],
        [121.1195, 134.3393],
        [ 21.6665,  38.3948],
        [ 98.9722, 116.9606],
        [ 55.9515,  69.5663],
        [ 80.1944,  99.7727],
        [121.2649, 134.8603],
        [ 22.9455,  39.4882],
        [ 99.8443, 118.0085],
        [ 56.8236,  70.6143],
        [ 79.3223,  98.7247],
        [121.5263, 134.3847],
        [ 20.7944,  37.3469],
        [100.2512, 118.0539]], grad_fn=<AddmmBackward>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [46]:
#We can use it to make predictions of crop yields for new regions by passing a batch containing a single row of input.

model(torch.tensor([[75, 63, 44.]]))

tensor([[53.3502, 67.5977]], grad_fn=<AddmmBackward>)