<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#PyTorch Basics (Tensor and Gradients)

#PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array.

In [2]:
import torch

In [3]:
# Number
t1 = torch.tensor(5.) # 5. is same as 5.0 a floating point number.
t1

tensor(5.)

In [4]:
print(t1.dtype)
t1.shape

torch.float32


torch.Size([])

In [5]:
# Vector
t2 = torch.tensor([1, 2., 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
print(t2.dtype)
t2.shape

torch.float32


torch.Size([4])

In [7]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
print(t3.dtype)
t3.shape

torch.float32


torch.Size([3, 2])

In [9]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [10]:
print(t4.dtype)
t4.shape

torch.float32


torch.Size([2, 2, 3])

In [11]:
#Tensor Operations and Gradients.
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [12]:
# Arithmetic operations
y = w * x + b
y

#What makes PyTorch unique is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. 
#This feature of PyTorch is called autograd (automatic gradients).

tensor(17., grad_fn=<AddBackward0>)

In [13]:
# Compute derivatives
y.backward()

#The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

In [14]:
# Display gradients
print('dy/dx:', x.grad) #Will print none because for x requires_grad is not set to true.
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

#The "grad" in w.grad is short for gradient, which is another term for derivative. 
#The term gradient is primarily used while dealing with vectors and matrices.

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [16]:
#PyTorch Conjuction with NumPy
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [17]:
#We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [19]:
#another method to covert from NumPy to tensor.
z = torch.tensor(x)
z

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [20]:
#tensor to NumPy
# Convert a torch tensor to a numpy array.
a = y.numpy()
a

array([[1., 2.],
       [3., 4.]])

In [ ]:
#You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with 
#multi-dimensional numeric data. There are two main reasons:
'''
Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.

GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a 
Graphics Processing Unit (GPU).
Computations that might typically take hours can be completed within minutes using GPUs.

'''

In [22]:
#Tensor Functions: For creating and manipulating the tensors.

# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [23]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [24]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [25]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])