<a href="https://colab.research.google.com/github/Saurav-Raghaw/Python/blob/main/PyTorch_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
########_________PyTorch Basic Operation__________##########

In [1]:
import torch

#1. torch.rand()

*  Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1).
*  For help run `?torch.rand()`

In [18]:
a = torch.rand(5)
print(a,'\n')

torch.rand(3, 5)

tensor([0.6845, 0.6370, 0.2613, 0.5022, 0.6408]) 



tensor([[0.3184, 0.0680, 0.2421, 0.1870, 0.0050],
        [0.3706, 0.4866, 0.1099, 0.3350, 0.9877],
        [0.2038, 0.5867, 0.6958, 0.3866, 0.2518]])

#2. torch.rand_like()
*  Returns a tensor with the same size as input that is filled with random numbers from a uniform distribution on the interval [0, 1) . 


In [24]:
t1 = torch.rand_like(a)
print(t1)

t2 = torch.rand(a.shape) #same as rand(with a.shape).
print(t2)

tensor([0.2195, 0.6093, 0.5904, 0.7406, 0.7221])
tensor([0.1635, 0.8888, 0.0301, 0.6452, 0.0613])


torch.float32

#3. torch.randint(start, end , size)
*  Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).

> *  start (int, optional) – Lowest integer to be drawn from the distribution. Default: 0.
*  end (int) – One above the highest integer to be drawn from the distribution.
*  size (tuple) – a tuple defining the shape of the output tensor.

In [27]:
t = torch.randint(3, 6, (10,))
print(t, '\n')

#DataTypes.
print(t2.dtype)
t.dtype

tensor([5, 5, 3, 5, 4, 3, 3, 5, 5, 4]) 

torch.float32


torch.int64

In [29]:
torch.randint(10, (3,3)) #start is 0.

tensor([[7, 4, 5],
        [3, 6, 5],
        [0, 2, 0]])

#4. torch.randn()
* Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).


In [30]:
torch.randn(5)

tensor([-0.4331, -0.9583, -0.3319, -1.1503,  0.5199])

In [31]:
torch.randn(4, 5)

tensor([[ 0.6037, -0.2700,  0.2843, -1.0879, -1.1512],
        [ 0.1958,  1.0823, -0.3895,  1.0206, -0.8872],
        [-1.0798, -0.8705, -0.4660,  0.4727, -0.1131],
        [-0.9025,  0.2551, -0.3048,  0.8060,  1.0945]])

#5. torch.randperm()
* Returns a random permutation of integers from 0 to n - 1.

In [32]:
torch.randperm(5)

tensor([2, 1, 3, 0, 4])

#6. torch.numel()
*  Returns the total number of elements in the input tensor.

In [40]:
t = torch.randn(4, 5)
print(t, '\n')
print('Length of t:', +torch.numel(t))

tensor([[ 0.9245, -0.2542, -0.4275, -1.3297,  0.5035],
        [-1.2464, -1.2554,  1.1284,  1.4145, -0.4358],
        [ 1.1167, -0.7841, -1.0878, -0.2742,  3.6850],
        [ 0.7516, -1.7655,  1.1681, -0.4039,  0.6874]]) 

Length of t: 20


#7. torch.zeros()
*  Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

In [43]:
t = torch.zeros(10)
t

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
t = torch.zeros(3, 5)
t

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [46]:
torch.zeros_like(t)

#Returns a tensor filled with the scalar value 0, with the same size as input. 
#torch.zeros_like(input) is equivalent to torch.zeros(input.size(), dtype=input.dtype, layout=input.layout, device=input.device).

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [48]:
t = torch.ones(4,5)
print(t)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [49]:
torch.ones_like(t)  #Returns a tensor filled with the scalar value 1, with the same size as input.

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [51]:
#torch.empty()

#Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument size.

torch.empty(2,3)

tensor([[2.8088e+34, 3.0950e-41, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 1.2751e-40]])

In [53]:
#torch.full()
#Creates a tensor of size size filled with fill_value. The tensor’s dtype is inferred from fill_value.

torch.full((3,4), 2.14674)

tensor([[2.1467, 2.1467, 2.1467, 2.1467],
        [2.1467, 2.1467, 2.1467, 2.1467],
        [2.1467, 2.1467, 2.1467, 2.1467]])

In [55]:
#torch.transpose()
t = torch.randn(3, 4)
t

tensor([[-0.1053, -0.9059,  2.0552,  0.0378],
        [-0.5946, -0.1392,  0.7254,  1.1007],
        [-0.3863,  0.7889, -0.1227, -0.6007]])

In [57]:
torch.transpose(t, 0, 1)

tensor([[-0.1053, -0.5946, -0.3863],
        [-0.9059, -0.1392,  0.7889],
        [ 2.0552,  0.7254, -0.1227],
        [ 0.0378,  1.1007, -0.6007]])

In [62]:
#torch.abs()
#Computes the absolute value of each element in input.

t = torch.randn(5)
t

tensor([ 0.1942, -0.6066,  1.0267,  0.2795, -1.5949])

In [63]:
torch.abs(t) #absolute value of each element.

tensor([0.1942, 0.6066, 1.0267, 0.2795, 1.5949])

In [64]:
#torch.acos
#Computes the inverse cosine of each element in input.

t = torch.randn(5)
t

tensor([-0.1400,  1.0957,  0.9070,  0.5290, -0.3028])

In [65]:
torch.acos(t)

tensor([1.7113,    nan, 0.4347, 1.0134, 1.8784])

#torch.add(input, other)
*  Adds the scalar `other` to each element of the input `input` and returns a new resulting tensor.

*  out=input+other

In [66]:
t = torch.randn(5)
t

tensor([-1.0009,  0.3310, -0.6285, -1.1551, -0.1357])

In [67]:
torch.add(t, 20)

tensor([18.9991, 20.3310, 19.3715, 18.8449, 19.8643])

#torch.add(input, other, alpha=1)
*  Each element of the tensor other is multiplied by the scalar alpha and added to each element of the tensor input. The resulting tensor is returned.
*  out = input + alpha × other

In [68]:
t1 = torch.randint(3, 6, (10,))
t1

tensor([3, 3, 5, 5, 3, 5, 3, 3, 4, 5])

In [69]:
t2 = torch.randint(3, 6, (10,))
t2

tensor([4, 3, 3, 5, 3, 3, 3, 3, 5, 5])

In [71]:
torch.add(t1, t2, alpha=10)

tensor([43, 33, 35, 55, 33, 35, 33, 33, 54, 55])

In [76]:
t1 = torch.randn(3)
print(t1, '\n')

t2 = torch.randn(4, 1)
print(t2, '\n')

print(torch.add(t1, t2, alpha=10))

tensor([-0.9761, -0.3137,  0.9136]) 

tensor([[ 0.5234],
        [-1.2397],
        [-0.9897],
        [-1.3131]]) 

tensor([[  4.2576,   4.9200,   6.1473],
        [-13.3727, -12.7103, -11.4831],
        [-10.8727, -10.2103,  -8.9830],
        [-14.1072, -13.4448, -12.2175]])


#torch.addcdiv(input, tensor1, tensor2, value=1)
*  Performs the element-wise division of `tensor1` by `tensor2`, multiply the result by the scalar `value` and add it to `input`.



> *  input (Tensor) – the tensor to be added
*  tensor1 (Tensor) – the numerator tensor
*  tensor2 (Tensor) – the denominator tensor
*  value (Number, optional) – multiplier for tensor1/tensor2

Integer division with addcdiv is no longer supported, and in a future release addcdiv will perform a true division of tensor1 and tensor2. 

In [82]:
input = torch.randint(3, 6, (10,))
print(input, '\n')

t1 = torch.randint(3, 6, (10,))
print(t1, '\n')

t2 = torch.randint(3, 6, (10,))
print(t2, '\n')

value= 10
print((input + value * torch.trunc(t1 / t2)).to(input.dtype), '\n')

print((input + value * t1 / t2))

tensor([3, 3, 5, 4, 4, 3, 3, 4, 5, 5]) 

tensor([3, 3, 3, 3, 5, 4, 4, 3, 3, 3]) 

tensor([5, 3, 3, 4, 3, 3, 5, 3, 3, 4]) 

tensor([ 3, 13, 15,  4, 14, 13,  3, 14, 15,  5]) 

tensor([ 9.0000, 13.0000, 15.0000, 11.5000, 20.6667, 16.3333, 11.0000, 14.0000,
        15.0000, 12.5000])


In [85]:
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
print(torch.addcdiv(t, t1, t2, value=0.1), '\n')

value=0.01
print((t + value * t1 / t2))

tensor([[  1.5354,  -1.0019,   0.4363],
        [  1.0643, -22.4808,   0.7804],
        [  1.7461,   8.6027,   0.2824]]) 

tensor([[ 1.5418, -0.7128,  0.4317],
        [ 1.4946, -2.8606,  0.4661],
        [ 1.5628,  0.2477,  0.4163]])


In [87]:
#torch.addcmul(input, tensor1, tensor2, value=1)

#Performs the element-wise multiplication of tensor1 by tensor2, multiply the result by the scalar value and add it to input.

input = torch.randint(3, 6, (10,))
print(input, '\n')

t1 = torch.randint(3, 6, (10,))
print(t1, '\n')

t2 = torch.randint(3, 6, (10,))
print(t2, '\n')

print(torch.addcmul(input, t1, t2, value=10))

tensor([5, 4, 4, 4, 4, 5, 5, 3, 4, 4]) 

tensor([3, 4, 5, 3, 4, 4, 3, 3, 4, 3]) 

tensor([4, 3, 5, 5, 3, 3, 4, 5, 5, 4]) 

tensor([125, 124, 254, 154, 124, 125, 125, 153, 204, 124])


In [89]:
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
print(torch.addcmul(t, t1, t2, value=0.1), '\n')

value=0.1
print((t + value * t1 * t2))

tensor([[0.6863, 0.3794, 0.9321],
        [0.6502, 0.4307, 0.9385],
        [0.6954, 0.3665, 0.9305]]) 

tensor([[0.6863, 0.3794, 0.9321],
        [0.6502, 0.4307, 0.9385],
        [0.6954, 0.3665, 0.9305]])


In [91]:
#torch.exp()
#Returns a new tensor with the exponential of the elements of the input tensor input.
t1 = torch.randint(3, 6, (10,))
torch.exp(t1)

tensor([ 54.5981, 148.4132, 148.4132,  20.0855,  20.0855,  54.5981,  54.5981,
         54.5981,  20.0855,  20.0855])

In [94]:
import math
t = torch.tensor([0, math.log(2.)])
print(t,'\n')
torch.exp(t)

tensor([0.0000, 0.6931]) 



tensor([1., 2.])

In [96]:
#torch.exp2()
#Computes the base two exponential function of input.

t = torch.tensor([0, math.log(2.), 2, 3])
print(t,'\n')
torch.exp2(t)

tensor([0.0000, 0.6931, 2.0000, 3.0000]) 



tensor([1.0000, 1.6168, 4.0000, 8.0000])

In [100]:
#torch.trunc(input)
#Returns a new tensor with the truncated integer values of the elements of input.

input  = torch.randn(4)
print(input, '\n')

print(torch.trunc(input))

tensor([-0.4473,  1.0704, -1.2216,  0.1048]) 

tensor([-0.,  1., -1.,  0.])


In [102]:
#torch.float_power(input, exponent)
#Raises input to the power of exponent, elementwise, in double precision. 
#If neither input is complex returns a torch.float64 tensor, and if one or more inputs is complex returns a torch.complex128 tensor.

t = torch.randint(3, 6, (4,))
print(t, '\n')

torch.float_power(t, 2)

tensor([4, 3, 5, 4]) 



tensor([16.,  9., 25., 16.], dtype=torch.float64)

In [103]:
#torch.log(input)
#Returns a new tensor with the natural logarithm of the elements of input.
#base is e

t = torch.randint(3, 6, (4,))
print(t, '\n')

torch.log(t)

tensor([4, 3, 5, 3]) 



tensor([1.3863, 1.0986, 1.6094, 1.0986])

In [104]:
#torch.log10(input)
#Returns a new tensor with the logarithm to the base 10 of the elements of input.
t = torch.randint(2, 20, (10,))
print(t, '\n')

torch.log10(t)

tensor([ 7, 10,  4, 10, 19, 15,  2, 10,  4, 17]) 



tensor([0.8451, 1.0000, 0.6021, 1.0000, 1.2788, 1.1761, 0.3010, 1.0000, 0.6021,
        1.2304])

In [105]:
#torch.pow(input, exponent)
#Takes the power of each element in input with exponent and returns a tensor with the result.

#exponent can be either a single float number or a Tensor with the same number of elements as input.

t = torch.randint(2, 20, (10,))
print(t, '\n')

torch.pow(t, 2)

tensor([ 2, 14,  8,  5, 14,  6,  4, 17, 15,  2]) 



tensor([  4, 196,  64,  25, 196,  36,  16, 289, 225,   4])

In [118]:
t = torch.randint(2, 20, (10,))
print(t, '\n')

print(t.add_(10, 2)) #In-place version


tensor([10,  8, 11, 13,  3,  3,  7,  5, 15, 18]) 

tensor([30, 28, 31, 33, 23, 23, 27, 25, 35, 38])


In [119]:
t = torch.randint(2, 20, (10,))
print(t, '\n')
print(t.add(10, 2))

tensor([18,  2,  8, 10,  2, 16,  5, 17,  7,  2]) 

tensor([38, 22, 28, 30, 22, 36, 25, 37, 27, 22])
